<?xml version="1.0"?>
    <robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="flir_blackflys">
    <!-- 
        camera_{x,y,z,mass} are physical properties of camera collision model
        lens_{r, h, mass} are physical properties of the camera lens
        hfov, fps, width, height, format, near, and far are simulation
    -->
    <xacro:macro name="flir_blackflys"
        params="frame:=camera name:=camera camera_x:=0.047758 camera_y:=0.029 camera_z:=0.029 camera_mass:=0.03
                lens_r:=0.016 lens_h:=0.04 lens_mass:= 0.05 
                hfov:=1.0471975512 fps:=30 width:=720 height:=540 format:=R8G8B8 near:=0.5 far:=300">
        
        <link name="${frame}"/>

        <joint name="${frame}_body_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${pi/2} ${-pi/2} 0" />
            <parent link="${frame}"/>
            <child link="${frame}_body"/>
        </joint>


        <link name="${frame}_body">
        <inertial>
            <mass value="${camera_mass}" />
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
        <visual>
            <origin xyz="0 0 0.01425" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://flir_camera_description/meshes/flir_blackflys.stl"/>
            </geometry>
            <material name="">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
            <!-- <material name="dark_grey" /> -->
        </visual>
        <collision>
            <origin xyz="0.003 0 ${camera_z/2}" rpy="0 0 0" />
            <geometry>
            <box size="${camera_x} ${camera_y} ${camera_z}" />
            </geometry>
        </collision>
        </link>

        <link name="${frame}_lens">
        <intertial>
            <mass values="${lens_mass}" />
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </intertial>
        <visual>
            <origin xyz="${lens_h/2} 0 0" rpy="0 1.5707 0" />
            <geometry>
            <cylinder radius="${lens_r}" length="${lens_h}"/>
            </geometry>
            <material name="">
                <color rgba="0.2 0.2 0.2 1" />
            </material>
            <!-- <material name="dark_grey" /> -->
        </visual>
        <collision>
            <origin xyz="${lens_h/2} 0 0" rpy="0 1.5707 0" />
            <geometry>
            <cylinder radius="${lens_r}" length="${lens_h}"/>
            </geometry>
        </collision>
        </link>

        <joint name="${frame}_lens_joint" type="fixed">
        <origin xyz="0.02685 0 0.01425" rpy="0 0 0" />
        <parent link="${frame}_body" />
        <child link="${frame}_lens" />
        </joint>

        <link name="${frame}_virtual_lens" />

        <joint name="${frame}_virtual_lens_joint" type="fixed">
        <origin xyz="${lens_h} 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
        <parent link="${frame}_lens" />
        <child link="${frame}_virtual_lens" />
        </joint>

        <link name="${frame}_optical" />

        <joint name="${frame}_optical_joint" type="fixed">
        <!-- Change made here compared to original rpy -pi/2 0 -pi/2 -->
        <origin xyz="0.03675341975118588
                    0.0011005389185428562
                    -0.010802901733302936" 
                rpy="0.0008015 -0.0685631 0.008044"/>
        <parent link="${frame}_virtual_lens" />
        <child link="${frame}_optical" />
        </joint>

        <link name="${frame}_optical_control_link"/>

        <joint name="${frame}_optical_control_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 ${pi}" />
        <parent link="${frame}_optical" />
        <child link="${frame}_optical_control_link" />
        </joint>

        <!-- Gazebo -->
        <!-- <gazebo reference="${frame}_optical">
        <material>Gazebo/Grey</material>
        <sensor type="camera" name="${name}">
            <update_rate>${fps}</update_rate>
            <camera name="${name}">
            <pose>0 0 0 0 -1.5707 1.5707</pose>
            <horizontal_fov>${hfov}</horizontal_fov>
            <image>
                <width>${width}</width>
                <height>${height}</height>
                <format>${format}</format>
            </image>
            <clip>
                <near>${near}</near>
                <far>${far}</far>
            </clip>
            <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.007</stddev>
            </noise>
            </camera>

            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>${fps}</updateRate>
            <cameraName>${name}</cameraName>
            <imageTopicName>image_raw</imageTopicName>
            <cameraInfoTopicName>camera_info</cameraInfoTopicName>
            <frameName>${frame}_optical</frameName>
            <hackBaseline>0.07</hackBaseline>
            <distortionK1>0.0</distortionK1>
            <distortionK2>0.0</distortionK2>
            <distortionK3>0.0</distortionK3>
            <distortionT1>0.0</distortionT1>
            <distortionT2>0.0</distortionT2>
            </plugin>
        </sensor>
        </gazebo> -->
    </xacro:macro>
</robot>
